apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pksv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pksv
    app.kubernetes.io/part-of: ci1t-830-0022-app
  name: devfile-sample-pksv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pksv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pksv
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0022-tenant/ci1t-830-0022-app/devfile-sample-pksv@sha256:d983908e7ee0e8750a111aa0954f5a057fa620d46d4155e91e9288f960c8dcd2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
